### ISSUE TITLE
Failed to resolve gradle dependency.

### ISSUE THREAD

**Issue by sandeshlasnapure** [HendraAnggrian/reveallayout#2]
Not able to add dependency.

**Comment by HendraAnggrian** [comment]
I'm sorry it was supposed to be `compile 'com.hendraanggrian:reveallayout:0.3.1'`, please try again.

**Comment by sandeshlasnapure** [comment]
Thanks for quick reply, will check.

**Comment by sandeshlasnapure** [comment]
Done, thanks

**Comment by sandeshlasnapure** [comment]
what is the min sdk version for this lib?

**Comment by HendraAnggrian** [comment]
For some reasons I yet to remember, the min sdk is 15 (Android 4.0.3), which is 1 level higher than needed in CircularReveal lib.
