### ISSUE TITLE
Activity transition stop in the middle (Asking for Enhancements)

### ISSUE THREAD

**Issue by AnthonyKoueik** [HendraAnggrian/reveallayout#3]
when try the Activity transition , the Reveal Transition animation stops in Middle and when Reverse it starts from the middle of the screen.
Is there anyway to make the Circle Reveal Transition to Make a full Screen animation and not Start|End in the middle ?

thank you

**Comment by HendraAnggrian** [comment]
Hi @AnthonyKoueik, I cannot reproduce the issue, would you mind sharing your code so that I may try it myself? Can you try the example app on your device and see if it is working correctly?

**Comment by AnthonyKoueik** [comment]
yes, Im just using your sample code. 
![image](https://user-images.githubusercontent.com/2689868/28018749-25a083e0-6587-11e7-9cac-5af00ee9477e.png)
even in your GIF you can see that the animation start from center of the screen when reverse

**Comment by HendraAnggrian** [comment]
@AnthonyKoueik okay I can see your point. Unfortunately, I'm currently in the process of turning most of my libraries to Kotlin. So it might take me some time to enhance this particular issue, I'll post you back in a week.

**Comment by AnthonyKoueik** [comment]
@HendraAnggrian Thank you, I will be waiting your post

**Comment by HendraAnggrian** [comment]
@AnthonyKoueik Thank you for waiting! Version 0.5.0 is out with larger end radius for smoother activity transition animation.

**Comment by AnthonyKoueik** [comment]
Cool :) looks promising ! i will try it out 
thank you
