### ISSUE TITLE
Do you have the code for this example?

### ISSUE THREAD

**Issue by lucasrafagnin** [hendraanggrian/reveallayout#5]
Do you have the code for this example? I could not play it in my app
https://github.com/HendraAnggrian/reveallayout/blob/master/art/demo2.gif

**Comment by hendraanggrian** [comment]
@lucasrafagnin sorry for late reply. Yes, the example folder is a module that holds source code of that demo gif.

**Comment by clevermatem** [comment]
@hendraanggrian  goodjob brah ,  keep it up (y)
