### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xperiafan13-rom** [hendraanggrian/reveallayout#6]
i follow your sample but i have this error:
kotlin.UninitializedPropertyAccessException: lateinit property rect has not been initialized
I put the same code that kotlin version

@BindExtra(EXTRA_RECT) lateinit var rect: Rect

**Comment by muhammad-zain** [comment]
Could not read script 'https://raw.githubusercontent.com/HendraAnggrian/hendraanggrian.github.io/master/bintray.gradle' as it does not exist.
<a href="openFile:/Users/zain/projects/socialview/socialview-commons/build.gradle">Open File</a>

**Comment by hendraanggrian** [comment]
I'm sorry for late reply.

@xperiafan13-rom the idea is to send `Rect` to next activity as extra. You may add extra manually by `Intent.addExtra`, or use [my other library](https://github.com/hendraanggrian/bundler) as seen on the example app.

@muhammad-zain that is my fault. There is going to be a major update with this lib, stay tuned in coming days/weeks.
